import mongoose from 'mongoose'
import { CHARGE_CATEGORIES, PAYMENT_METHODS } from './constants.js'

const chargeSchema = new mongoose.Schema(
  {
    amount: { type: Number, required: true, min: 0 },
    date: { type: Date, required: true, default: Date.now, index: true },
    category: { type: String, enum: CHARGE_CATEGORIES, required: true, index: true },
    supplier: String,
    paymentMethod: { type: String, enum: PAYMENT_METHODS, default: 'especes' },
    receiptUrl: String,
    comment: String,

    /* "Cette charge concerne : un véhicule / la société." A vehicle-scoped
       charge is what makes per-vehicle profitability possible. */
    scope: { type: String, enum: ['vehicle', 'company'], required: true, index: true },
    vehicle: { type: mongoose.Schema.Types.ObjectId, ref: 'Vehicle', index: true },

    /* Set when the charge was generated by completing a maintenance job,
       so the two stay linked rather than double-entered. */
    maintenance: { type: mongoose.Schema.Types.ObjectId, ref: 'Maintenance' },

    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
)

chargeSchema.pre('validate', function (next) {
  if (this.scope === 'vehicle' && !this.vehicle) {
    return next(new Error('Une charge liée à un véhicule doit désigner ce véhicule.'))
  }
  if (this.scope === 'company') this.vehicle = undefined
  next()
})

export const Charge = mongoose.model('Charge', chargeSchema)
