import express from 'express'
import cors from 'cors'
import morgan from 'morgan'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { env, isProd } from './config/env.js'
import { errorHandler, notFound } from './middleware/error.js'

import publicRoutes from './routes/public.js'
import authRoutes from './routes/auth.js'
import dashboardRoutes from './routes/dashboard.js'
import vehicleRoutes from './routes/vehicles.js'
import clientRoutes from './routes/clients.js'
import reservationRoutes from './routes/reservations.js'
import planningRoutes from './routes/planning.js'
import financeRoutes from './routes/finance.js'
import maintenanceRoutes from './routes/maintenance.js'
import quoteRoutes from './routes/quoteRequests.js'
import settingsRoutes from './routes/settings.js'
import userRoutes from './routes/users.js'
import uploadRoutes from './routes/uploads.js'
import { ensureRoot, uploadRoot, PUBLIC_PREFIX } from './services/storage.js'

export function createApp() {
  const app = express()

  app.set('trust proxy', 1)
  app.use(express.json({ limit: '2mb' }))
  app.use(express.urlencoded({ extended: true }))
  app.use(morgan(isProd ? 'combined' : 'dev'))

  /*
   * CORS applies to the API only.
   *
   * Two things this has to get right, both learned the hard way once the app
   * started serving its own front end:
   *
   *  - Vite marks its module script and stylesheet `crossorigin`, so the
   *    browser sends an Origin header even for same-origin asset requests.
   *    Gating static files on the allowlist meant every asset 500'd and the
   *    page loaded with no CSS and no JS.
   *  - A disallowed origin is not a server error. Throwing from the callback
   *    turns it into a 500; the correct response is simply to omit the CORS
   *    headers and let the browser enforce its own policy.
   */
  const corsMiddleware = cors((req, cb) => {
    const origin = req.headers.origin
    if (!origin) return cb(null, { origin: true, credentials: true })

    let sameOrigin = false
    try {
      sameOrigin = new URL(origin).host === req.headers.host
    } catch {
      /* malformed Origin header — treat as cross-origin */
    }

    const allowed = sameOrigin || env.corsOrigins.includes(origin)
    cb(null, { origin: allowed, credentials: true })
  })

  app.use('/api', corsMiddleware)

  app.get('/api/health', (_req, res) => {
    res.json({ ok: true, env: env.nodeEnv, time: new Date().toISOString() })
  })

  /* Public site — no authentication. Never exposes the Car Wash fleet. */
  app.use('/api', publicRoutes)

  /* Dashboard. */
  app.use('/api/auth', authRoutes)
  app.use('/api/dashboard', dashboardRoutes)
  app.use('/api/vehicles-admin', vehicleRoutes)
  app.use('/api/clients', clientRoutes)
  app.use('/api/reservations-admin', reservationRoutes)
  app.use('/api/planning', planningRoutes)
  app.use('/api/finance', financeRoutes)
  app.use('/api/maintenance', maintenanceRoutes)
  app.use('/api/quote-requests-admin', quoteRoutes)
  app.use('/api/settings', settingsRoutes)
  app.use('/api/users', userRoutes)
  app.use('/api/uploads', uploadRoutes)

  /* ---------------------------------------------------------------
     Uploaded files.

     User-supplied bytes, so they are served defensively: nosniff, a
     Content-Security-Policy that neuters anything script-like that slipped
     through the type allowlist, and no directory listing. Filenames are
     random hex generated by us, so they can be cached hard.
  ---------------------------------------------------------------- */
  ensureRoot()
  app.use(
    PUBLIC_PREFIX,
    express.static(uploadRoot, {
      index: false,
      dotfiles: 'deny',
      fallthrough: false,
      maxAge: '365d',
      immutable: true,
      setHeaders(res) {
        res.setHeader('X-Content-Type-Options', 'nosniff')
        res.setHeader('Content-Security-Policy', "default-src 'none'; sandbox")
        res.setHeader('Cross-Origin-Resource-Policy', 'same-origin')
      },
    })
  )

  /* ---------------------------------------------------------------
     Serve the built front end, when there is one.

     Keyed on the build existing rather than on NODE_ENV, so a local
     `npm run build` is exercised the same way production is. In dev the
     Vite server on :5173 is what you hit, and this simply does nothing.
  ---------------------------------------------------------------- */
  const here = path.dirname(fileURLToPath(import.meta.url))
  const clientDist = path.resolve(here, '../../client/dist')
  const indexHtml = path.join(clientDist, 'index.html')

  if (fs.existsSync(indexHtml)) {
    app.use(
      express.static(clientDist, {
        index: false,
        // Vite fingerprints everything under /assets, so it can be cached
        // hard; index.html must never be, or a deploy goes unnoticed.
        setHeaders(res, filePath) {
          if (filePath.includes(`${path.sep}assets${path.sep}`)) {
            res.setHeader('Cache-Control', 'public, max-age=31536000, immutable')
          } else {
            res.setHeader('Cache-Control', 'no-cache')
          }
        },
      })
    )

    /* SPA fallback: any GET that is not an API call and not a real file
       gets index.html, so deep links like /dashboard/flotte work on a
       hard refresh. Written as middleware rather than a wildcard route —
       Express 5 routes go through path-to-regexp v8, where a bare '*' is
       no longer a valid pattern. */
    app.use((req, res, next) => {
      if (req.method !== 'GET' || req.path.startsWith('/api/')) return next()
      // Explicit: sendFile would otherwise default to max-age=0, and this
      // header is the whole reason a redeploy is picked up rather than
      // people sitting on a stale index that points at old asset hashes.
      res.sendFile(indexHtml, { headers: { 'Cache-Control': 'no-cache' } })
    })

    console.log(`[api] serving the built client from ${clientDist}`)
  } else {
    console.log('[api] no client build found — API only (run `npm run build` in client/)')
  }

  app.use(notFound)
  app.use(errorHandler)

  return app
}
