import multer from 'multer'
import { env } from '../config/env.js'
import { ApiError } from './error.js'
import {
  ACCEPTED_LABEL,
  ensureRoot,
  isAccepted,
  newKey,
  uploadRoot,
} from '../services/storage.js'

/**
 * Multipart handling.
 *
 * Two limits matter: the byte size, and the set of types we are willing to
 * serve back. Anything outside the allowlist is rejected before it reaches
 * disk, and the stored filename is generated by us, never taken from the
 * client.
 */

const storage = multer.diskStorage({
  destination(_req, _file, cb) {
    try {
      cb(null, ensureRoot())
    } catch (err) {
      cb(err)
    }
  },
  filename(_req, file, cb) {
    cb(null, newKey(file.mimetype))
  },
})

function fileFilter(_req, file, cb) {
  if (!isAccepted(file.mimetype)) {
    return cb(new ApiError(415, `Format non accepté. Formats admis : ${ACCEPTED_LABEL}.`))
  }
  cb(null, true)
}

const limits = {
  fileSize: env.maxUploadMb * 1024 * 1024,
  files: 8,
}

export const uploadSingle = multer({ storage, fileFilter, limits }).single('file')
export const uploadMany = multer({ storage, fileFilter, limits }).array('files', 8)

/** Turns multer's own errors into our API error shape. */
export function handleUpload(handler) {
  return (req, res, next) =>
    handler(req, res, (err) => {
      if (!err) return next()
      if (err instanceof multer.MulterError) {
        if (err.code === 'LIMIT_FILE_SIZE') {
          return next(new ApiError(413, `Fichier trop volumineux (maximum ${env.maxUploadMb} Mo).`))
        }
        if (err.code === 'LIMIT_FILE_COUNT') {
          return next(new ApiError(413, 'Trop de fichiers envoyés en une fois.'))
        }
        return next(new ApiError(400, `Envoi refusé : ${err.code}.`))
      }
      next(err)
    })
}

export { uploadRoot }
